version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 2717:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
# docker run -d -p 2717:27017 -v ~/mongodb-latest:/data/db --name mymongo mongo:latest
